# Generated by Django 3.2 on 2022-08-11 17:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20220810_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookitem',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('0c443be6-f523-4994-9a97-1d1df0c4140b')),
        ),
    ]
